### ISSUE TITLE
Progress 内部数据 settimeout 无法同步更新

### ISSUE THREAD

**Issue by asurance** [arco-design/arco-design-mobile#104]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.25.4
- **Phone Model And Version:** PC就可以复现
- **Reproduction Link:** https://codepen.io/asurance/pen/abaYpWm?editors=ADM

## What is expected?
进度条上数据和按钮上数据一致

## Steps to reproduce
点击按钮，等待进度刷新

**Comment by ChelesteWang** [comment]
可以尝试颠倒 setLoading 和 setPercent 一达成你的目标

```tsx
const { React, Arco, ArcoIcon } = window;
const { Progress,Button } = Arco;
import {useEffect,useState} from "react";

 function ProgressDemo() {
   const [percent,setPercent] = React.useState(50);
   const [loading,setLoading] = React.useState(false);
    return (
      <div>
        {loading?'loading':<Progress percentage={percent}/>}
        <Button onClick={()=>{
          setLoading(true)
          setTimeout(()=>{
             setPercent(Math.random()*100);
             setLoading(false);
          },1000)
        }}>{percent}</Button>
      </div>
    );
}
ReactDOM.render(<ProgressDemo/>, mountNode);
```
