### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by zhangjiahao93** [arco-design/arco-design-mobile#126]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.27.2
- **Phone Model And Version:** pc chrome dev

## What is expected?
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition3 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:xxxx

## Steps to reproduce
use DatePicker component and use React.StrictMode

**Comment by ChelesteWang** [comment]
Can you provide a minimalist replay demo @zhangjiahao93

**Comment by zhangjiahao93** [comment]
@ChelesteWang 

https://github.com/zhangjiahao93/arco-mobile-issue

**Comment by ChelesteWang** [comment]
@zhangjiahao93 Now that we know the problem let's look at how do we solve it

**Comment by ziqisia** [comment]
@zhangjiahao93 I've located the problem, and it will be fixed in a later version
