### ISSUE TITLE
windows11项目启动失败

### ISSUE THREAD

**Issue by CoderSerio** [arco-design/arco-design-mobile#127]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.27.4
- **Phone Model And Version:** （无）

## Extra info
1. 具体报错情况：启动时import的路径会被错误解析，`packages\arcodesign\components`会被解析为`packagesarcodesigncomponents`
2. 尝试过全局替换`packages\arcodesign\components`中的反斜杠为`\\`和`/`，偶然成功启动过一段时间，但不久后自动还原又开始报错
3. 参考了issue #98，大概都是windows的问题，但是报错的场景不太一样，所里这里又提了一个issue

## What is expected?
windows11下能够进行开发

## Steps to reproduce
1. windows11，Node v16.19.0
2. 项目根目录下执行 npm run start或npm run start:vite等命令均启动失败(但PC文档可以启动)，具体失败原因见`Extra Info`

**Comment by AllianceTing** [comment]
follow +1

**Comment by ChelesteWang** [comment]
@AllianceTing @CoderSerio Can you provide detailed error stack contents and screenshots

**Comment by AllianceTing** [comment]
wait a monment

**Comment by AllianceTing** [comment]
just a moment

**Comment by AllianceTing** [comment]
use npm run start shown
![image](https://github.com/arco-design/arco-design-mobile/assets/72297937/0bdf2308-5df7-4dcd-b958-71b91e8694b4)

**Comment by CoderSerio** [comment]
My case is different....
I tried to replace the `\` in the path with `/` or `\\` globally,  but nothing worked cuz it seems generated  automatically with some config files...
![image](https://github.com/arco-design/arco-design-mobile/assets/79406469/dadb358a-cc4b-4dc3-8ff7-7d753598b5ae)

**Comment by AllianceTing** [comment]
i hava the same case as follow

**Comment by ChelesteWang** [comment]
> My case is different.... I tried to replace the `\` in the path with `/` or `\\` globally, but nothing worked cuz it seems generated automatically with some config files... ![image](https://user-images.githubusercontent.com/79406469/243151995-dadb358a-cc4b-4dc3-8ff7-7d753598b5ae.png)

@CoderSerio The reason for this problem is that \\ needs to be shred on Windows, and single \ doesn't make sense for escaping

**Comment by ChelesteWang** [comment]
I've tried to replicate this, but the main problem is that path escapes to \\ and ${code.replace(reg, '.. /.. /.. /.. /.. /${compFolder}`).replace(/\/esm\//g, '/')}`;  It is used for the introduction of ESM and therefore does not need to be escaped as path. As we all know, ESM parsing does not support \, so there will be an error message for related problems @CoderSerio You can refer to the document below to try to fix the current problem. I look forward to your contribution https://github.com/jiangjiu/blog-md/issues/47 ，

**Comment by CoderSerio** [comment]
thanks, I get it! 
I'll try to resolve it  tonight after work
