### ISSUE TITLE
Classname prefix 'arco-' is same as Arco Web would not conflict ?

### ISSUE THREAD

**Issue by pwcong** [arco-design/arco-design-mobile#14]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.19.0

**Comment by TinaPeach** [comment]
Usually Arco Mobile & Arco PC would not be used at the same time. If so, you can use ContextProvider and change the `prefixCls` property, and change the less variable `prefix` through `modifyVars` in less options.
