### ISSUE TITLE
如何和pc端arco组件做样式隔离

### ISSUE THREAD

**Issue by 97Ronal** [arco-design/arco-design-mobile#142]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.28.0

## What is expected?
一个项目里引入了arco和arco-mobile，发现mobile的样式似乎污染了arco/webreact的样式

**Comment by TinaPeach** [comment]
同学，可以参考下这个：https://github.com/arco-design/arco-design-mobile/issues/14

**Comment by JNUfeatherwit** [comment]
> 同学，可以参考下这个：#14

两个库使用的前缀变量都是@prefix，没法单独改变其中一个啊
