### ISSUE TITLE
avatar组件在使用字体头像的时候，src必填导致ts报错

### ISSUE THREAD

**Issue by halaproliu** [arco-design/arco-design-mobile#144]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.28.0
- **Phone Model And Version:** any

## What is expected?
看了下源码，字体组件期望的是src为undefined，并且没有children传入。然而src却是必填

## Steps to reproduce
在ts环境下输入<Avatar size="small" textAvatar="张"></Avatar>

**Comment by TinaPeach** [comment]
@halaproliu 同学，该问题已修复，近期发版：https://github.com/arco-design/arco-design-mobile/pull/145/files

**Comment by TinaPeach** [comment]
@halaproliu 新版本`@arco-design/mobile-react@2.28.1`已发布~

**Comment by halaproliu** [comment]
> @halaproliu 新版本`@arco-design/mobile-react@2.28.1`已发布~

好的
