### ISSUE TITLE
Input组件，PC上onClear设置value为''，点击无效，但是在移动端是生效的

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#154]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.29.0

**Comment by TinaPeach** [comment]
@2513483494 同学，[官网demo](https://arco.design/mobile/react/arco-design/pc/#/components/input)上是ok的（基础用法的第二个输入框），你的用法跟官网demo上有什么区别吗，可以看下你那边pc端点击清除是否生效，不行发一下使用的代码？

**Comment by 2513483494** [comment]
> @2513483494 同学，[官网demo](https://arco.design/mobile/react/arco-design/pc/#/components/input)上是ok的（基础用法的第二个输入框），你的用法跟官网demo上有什么区别吗，可以看下你那边pc端点击清除是否生效，不行发一下使用的代码？

clearShowType='always'   PC clearShowType设置成always才会生效。

**Comment by 2513483494** [comment]
可以试一下，把clearShowType设置为always注释掉，使用默认值，就会发现PC清除按钮不生效了

**Comment by 2513483494** [comment]
https://codepen.io/2513483494/pen/VwqZOKj?editors=ADM

**Comment by TinaPeach** [comment]
@2513483494 复现了，我们看看~

**Comment by TinaPeach** [comment]
@2513483494 https://github.com/arco-design/arco-design-mobile/pull/156 已在此mr修复，下周发版

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.29.1` 已修复
