### ISSUE TITLE
Dialog里面的Radio是无法变更value的，好奇怪，详情里面有codeopen案例

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#157]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.29.1

## Steps to reproduce
详情请看这个代码案例，我无法变更选项内容了
https://codepen.io/2513483494/pen/NWePLoR?editors=1111

**Comment by 2513483494** [comment]
const { React, Arco, ArcoIcon } = window;
const { Dialog, Cell, Button, Radio } = Arco;

 function DialogDemo() {
    const [visible, setVisible] = React.useState(false);
    const [v, setv] = React.useState(1);
    return (<div>
        <Button onClick={() => {
    Dialog.confirm({
      platform: 'ios',
      title: '风险忽略原因',
      children: (
        <>
          <Radio.Group
            value={v}
            onChange={setv}
          >
            <Radio value={1}>已有拜访</Radio>
            <Radio value={2}>已与客户沟通</Radio>
            <Radio value={3}>其他</Radio>
          </Radio.Group>
        </>
      ),
    });
    }}>111</Button>
    </div>);
}
ReactDOM.render(<DialogDemo/>, mountNode);

**Comment by CNlitai** [comment]
hello change your code
```
onChange={value => {
    setv(value);
}}
```
try again

**Comment by TinaPeach** [comment]
@2513483494 同学，通过方法(Dialog.confirm)调用的组件，不属于你当前组件的子组件，自然也不会参与当前组件的生命周期，即在当前组件的value这个state变化的时候，不会触发Dialog的children的重绘。这里2个选择：1. Radio去掉value属性，不使用受控模式；2. Dialog使用组件形式调用而非方法调用

**Comment by 2513483494** [comment]
晓得了
