### ISSUE TITLE
Popover  defaultVisible为true的时候,不生效,刷新页面仍然是没有显示出来

### ISSUE THREAD

**Issue by rockey2020** [arco-design/arco-design-mobile#159]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.29.2
- **Phone Model And Version:** chrome

<img width="357" alt="image" src="https://github.com/arco-design/arco-design-mobile/assets/64777114/18cd88f8-47c4-45cf-9214-d094718cbf87">

**Comment by TinaPeach** [comment]
@rockey2020 同学，问题已复现并修复，本周发版

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.29.3` 新版本中已解决
