### ISSUE TITLE
吹爆（这不是bugissues）

### ISSUE THREAD

**Issue by Tenodec** [arco-design/arco-design-mobile#16]
千呼万唤始出来，终于来了，不过为啥版本是2+，内部一直在使用的吗

**Comment by ChelesteWang** [comment]
Arco design mobile 迄今为止已在字节内部迭代了两年，包括头条、西瓜、番茄小说、抖音、懂车帝等在内的 10+ 业务已接入，内部 npm 包周下载量已近 1 万，多个重要组件已在线上有了较成熟的迭代优化。

**Comment by yaphetswtl519** [comment]
是的，0.x 1.x版本一直在内部使用优化迭代~
