### ISSUE TITLE
ImagePreview 关闭的时候会有延迟,会等一段时间,然后才开始关闭(进入到动画过渡环节)

### ISSUE THREAD

**Issue by rockey2020** [arco-design/arco-design-mobile#160]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.29.2
- **Phone Model And Version:** chrome
- **Reproduction Link:** https://arco.design/mobile/react/arco-design/pc/#/components/image-preview

## Steps to reproduce
官方的例子就有这个问题

**Comment by TinaPeach** [comment]
@rockey2020 同学，这个是因为需要判断用户在双击还是单击，双击是放大单击是关闭，所以需要等待几百ms，当用户未进行下一次点击时再关闭，否则执行双击事件

**Comment by rockey2020** [comment]
@TinaPeach 可否把双击单击的判断逻辑只放在固定的区域  这样我点击遮罩关闭的时候就不需要等这么久了

<img width="497" alt="image" src="https://github.com/arco-design/arco-design-mobile/assets/64777114/efc4bd59-e02d-4a33-ade2-fd919f206ece">

**Comment by rockey2020** [comment]
而且我觉得在遮罩层右上角增加一个x关闭按钮会更好点

**Comment by TinaPeach** [comment]
> 

这个不太好改，会有breaking change。发现代码里有重复的延时处理，我们改下，可以优化关闭蒙层的速度到200ms。

**Comment by TinaPeach** [comment]
> 而且我觉得在遮罩层右上角增加一个x关闭按钮会更好点

自定义的dom可以在images的各元素中传入extraNode实现。如果需要全局唯一的自定义dom，我们可以新提供一个 extra 属性。

**Comment by TinaPeach** [comment]
https://github.com/arco-design/arco-design-mobile/pull/161/files 上述修改在该MR中已支持

**Comment by rockey2020** [comment]
@TinaPeach 感谢大佬
