### ISSUE TITLE
Input可以适配在PC移动端都是输入中文的过程中不触发onChange，建议加一个props实现

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#166]
目前是有一个I
OS设备生效的props，能否这个props对所有设备都生效呢。
（我测试IOS设备也不生效，而且有bug）

**Comment by TinaPeach** [comment]
当前提供了`blockChangeWhenCompositing`属性，用于在ios输入中文时不触发onChange。这个有问题的话，可以提供下复现环境。其他（如安卓）设备无法监听，因为仅当ios系统键盘在输入中文时，会将拼音先置入input中，并且提供`compositionstart`和`compositionstart`系统事件供监听。安卓键盘仅当确认中文字后才会置入input，在置入之前，前端都无法感知到input的变化，即使有机型会置入input，没有触发 composition 相关事件，也是无法区分是否正输入中文的。
