### ISSUE TITLE
Tabs在移动端主动切换tab又bug

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#167]
https://codepen.io/2513483494/pen/rNomNEM?editors=0000

看这个代码案例，打开浏览器的移动端模拟，是无法切换的，因为切换后又切换回来了，关闭移动端模拟，表现正常。

猜测：移动端主动切换tab后，触发了touch相关事件导致。

**Comment by TinaPeach** [comment]
同学，该问题已复现并修复，本周发版

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.29.4`已发版修复
