### ISSUE TITLE
Tabs滑动时偶尔有bug

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#171]
<img width="509" alt="截屏2023-09-13 11 36 47" src="https://github.com/arco-design/arco-design-mobile/assets/48058550/a529582b-23a0-48e1-b277-80339727f26a">
在谷歌浏览器移动端模拟的时候，滑动一小段距离，有时候会出现这个问题。

**Comment by TinaPeach** [comment]
具体是什么问题不符合预期呢

**Comment by 2513483494** [comment]
> 具体是什么问题不符合预期呢

偶尔滑动后Tabs会像截图中一样，卡在中间，尝试升级版本到2.29.4,一样会有问题
