### ISSUE TITLE
Dialog在PC上丢失很多样式

### ISSUE THREAD

**Issue by 2513483494** [arco-design/arco-design-mobile#176]
PC：
<img width="786" alt="截屏2023-09-19 10 40 22" src="https://github.com/arco-design/arco-design-mobile/assets/48058550/838f2b09-4e52-4642-a887-8bcf89246481">

移动：
<img width="392" alt="截屏2023-09-19 10 40 43" src="https://github.com/arco-design/arco-design-mobile/assets/48058550/1bdb18a8-f2a4-44c3-a67c-13225d18ffed">

**Comment by 2513483494** [comment]
感觉是不是在pc上也兼容一下，目前项目里面是手动添加了一些样式做了pc的兼容

**Comment by TinaPeach** [comment]
@2513483494 Dialog有一个`platform`属性表示弹窗的样式类型，默认跟随系统（安卓或ios），你在pc上用，手动指定platform="ios"就可以了哈
