### ISSUE TITLE
PullRefresh存在严重的性能问题

### ISSUE THREAD

**Issue by rockey2020** [arco-design/arco-design-mobile#178]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.29.4
- **Phone Model And Version:** 小米13pro

在pc没出现卡顿,到了手机上就掉帧,完全没办法使用

**Comment by rockey2020** [comment]
<img width="366" alt="image" src="https://github.com/arco-design/arco-design-mobile/assets/64777114/40f484e9-81a9-4535-8a35-1985a553acb3">

强制改成这样可以临时改善卡顿的问题,但是下拉会有莫名的停顿效果,但是至少还能用

<img width="628" alt="image" src="https://github.com/arco-design/arco-design-mobile/assets/64777114/c6a2d90d-ef9c-409b-ad55-df3988bf5b01">

0的时候卡成ppt

**Comment by TinaPeach** [comment]
@rockey2020 这个写法确实不好，我们优化下重新发个包哈

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.29.5`中已修复

**Comment by chen8520** [comment]
![Image](https://github.com/user-attachments/assets/3cc1f9d0-80f3-4350-a88a-3f9d684d529d)

https://github.com/user-attachments/assets/770793fe-11df-4e58-b944-8613d5d66f72

手机上还是非常卡
