### ISSUE TITLE
Sub scrollable container in Popup can not scroll

### ISSUE THREAD

**Issue by pwcong** [arco-design/arco-design-mobile#20]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.19.0
- **Phone Model And Version:** iOS 15

![QElIDDBmAm](https://user-images.githubusercontent.com/13917544/181517280-7f810960-fa0d-497a-808f-918b7f51b481.jpg)

**Comment by TinaPeach** [comment]
![image](https://user-images.githubusercontent.com/106640896/182077456-c95ab877-68e2-45c3-85ed-c2d8be40b24a.png)
