### ISSUE TITLE
Support the ability to upload files. 支持上传文件的能力

### ISSUE THREAD

**Issue by adaex** [arco-design/arco-design-mobile#245]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## What problem does this feature solve?
Currently, only ImagePicker supports the feature of image uploading. It is expected that a new component can be added to support the uploading of regular files.
> 目前只有 ImagePicker 可以支持图片上传的功能，预期新增一个组件，可以支持普通文件的上传

## What are the similar cases of this feature
Similar to this: https://vant-ui.github.io/vant/#/zh-CN/uploader. However, only the file upload feature needs to be referenced, as the image preview functionality is almost identical to our ImagePicker.
![image](https://github.com/arco-design/arco-design-mobile/assets/29560987/c082ccff-d7ed-4fa6-a070-9162902d0a99)

> 类似这个组件 https://vant-ui.github.io/vant/#/zh-CN/uploader. 不过仅仅需要参考这里面的上传文件功能，其他的图片上传和预览等和我们的 ImagePicker 几乎是一致的

**Comment by adaex** [comment]
We can discuss this together if you are interested in this feature.
> 感兴趣可以一起讨论

**Comment by jianyi-gronk** [comment]
I would like to ask if there is any specific design drawing for the style of the file upload component.
For example, if I upload a text file, what should its preview style be like?
