### ISSUE TITLE
error while start with yarn start @babel/runtime/helpers/extends

### ISSUE THREAD

**Issue by hunter-xue** [arco-design/arco-design-mobile#256]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.31.1

## Steps to reproduce
yarn start after install

**Comment by hunter-xue** [comment]
resolved by install babel/runtime.

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.31.2` 已修复
