### ISSUE TITLE
Carousel 设置 offsetBetween 值时不能循环轮播

### ISSUE THREAD

**Issue by guangzan** [arco-design/arco-design-mobile#259]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## What problem does this feature solve?
Carousel 设置 offsetBetween 值时支持循环轮播

## Extra info
或者有临时解决方案吗

**Comment by adaex** [comment]
@guangzan  可以设置 fakeItem=true 来支持循环播放，详见文档 https://arco.design/mobile/react/arco-design/pc/#/components/carousel

![image](https://github.com/arco-design/arco-design-mobile/assets/29560987/5eabcb0d-7f2c-4868-a7fb-95e51597e428)

**Comment by guangzan** [comment]
Hi, @adaex,

感谢回复，抱歉我没有仔细查看文档。
