### ISSUE TITLE
Form组件的required如果未填可以改用label提示为必填项提示吗？还是说有什么方法可以设置，我没发现

### ISSUE THREAD

**Issue by limingxxoo** [arco-design/arco-design-mobile#264]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 

![微信截图_20240512111724](https://github.com/arco-design/arco-design-mobile/assets/20850802/87604b62-1f11-4330-bebc-cdff71cb9b66)

**Comment by wjyzhixing** [comment]
怎么解决的？
