### ISSUE TITLE
适配移动端异常

### ISSUE THREAD

**Issue by bingqichen** [arco-design/arco-design-mobile#43]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.20.0
- **Phone Model And Version:** chrome模拟器

## Steps to reproduce
我的配置是vite + arco mobile，发现在页面中写的自己的样式不会将px转为rem，是不是除了框架的组件，其他的项目代码是需要自己转换的？

**Comment by TinaPeach** [comment]
框架内部的样式已经是用rem的方式输出的了，并不带pxtorem的插件；如果是自己的样式，需要安装这个插件哈

**Comment by bingqichen** [comment]
> 框架内部的样式已经是用rem的方式输出的了，并不带pxtorem的插件；如果是自己的样式，需要安装这个插件哈

好的👌
