### ISSUE TITLE
是否支持react-native?

### ISSUE THREAD

**Issue by yibird** [arco-design/arco-design-mobile#58]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## What are the similar cases of this feature
现在主流的react-native的UI库垃圾的像狗屎,外国人的审美太拉了

## What problem does this feature solve?
是否有计划支持react-native?

**Comment by TinaPeach** [comment]
@yibird 同学，rn暂时没有计划支持哈，ui组件强依赖dom操作，暂时没有人力重写一次逻辑~❤

**Comment by byk04712** [comment]
好悲伤,这么漂亮的ui库居然不支持react-native.
