### ISSUE TITLE
Textarea 组件初始值为null会报错

### ISSUE THREAD

**Issue by 513205785Xie** [arco-design/arco-design-mobile#70]
初始赋值：
![image](https://user-images.githubusercontent.com/22184621/202466200-ecd0b141-41c7-4011-ac91-09b081d8b7de.png)
![image](https://user-images.githubusercontent.com/22184621/202466290-981c1b48-ea50-416b-a75b-10de82d2aeea.png)
表现：
![image](https://user-images.githubusercontent.com/22184621/202466375-b73bc8c2-61fe-432a-98aa-72e1e7c7c24e.png)
报错代码：
![image](https://user-images.githubusercontent.com/22184621/202466477-973895d3-8758-4977-9925-0d6d52e54322.png)

**Comment by CNlitai** [comment]
此问题已被修复 请保证版本不低于2.25.2 [https://github.com/arco-design/arco-design-mobile/commit/8cbf72525a64ad5a23ca7d36a8f77953d97b98c9](url)
