### ISSUE TITLE
组件库无法在nextjs中正常工作

### ISSUE THREAD

**Issue by theShapeOfvoice** [arco-design/arco-design-mobile#81]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.24.2
- **Phone Model And Version:** 本地chrome浏览器
- **Reproduction Link:** https://codesandbox.io/p/sandbox/quizzical-star-lz4e11

## What is expected?
期望可以在nextjs中正常使用，或者可以有一份对应的接入文档

## Steps to reproduce
https://lz4e11-3000.preview.csb.app/

**Comment by theShapeOfvoice** [comment]
在`nextjs`中引入`css`方式改为：`import '@arco-design/mobile-react/dist/style.min.css'`

然后在`_app.tsx`中`useEffect`调用`setRootPixel`方法可以正常使用了

`
import { useEffect } from 'react'
import '@arco-design/mobile-react/dist/style.min.css'
import type { AppProps } from 'next/app'
import Layout from '../Layout/Layout'
import { ContextProvider } from '@arco-design/mobile-react/cjs'
import setRootPixel from '@arco-design/mobile-react/tools/flexible';

export default function App({ Component, pageProps }: AppProps) {
  useEffect(()=>{
    setRootPixel(37.5);
  },[])
  return (
    <ContextProvider system="ios">
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ContextProvider>
  )
}`

不过还是希望官方能给一个接入说明

**Comment by laogui** [comment]
setRootPixel(37.5) 是全局的，最好是有个单独针对arco ui的基准尺寸配置，目前想在next里用这个库不太方便

**Comment by dukeluo** [comment]
@aiden-art  通过直接导入 css 的这种方式：`import '@arco-design/mobile-react/dist/style.min.css'`，可以支持修改主题变量吗
