### ISSUE TITLE
Could not resolve "@babel/runtime/helpers/extends 

### ISSUE THREAD

**Issue by Tenodec** [arco-design/arco-design-mobile#95]
vite 引入 报错Could not resolve "@babel/runtime/helpers/extends

**Comment by hunter-xue** [comment]
依然有这个问题，如何解决呢？

**Comment by TinaPeach** [comment]
抱歉这个issue漏掉了，这个问题是因为我们在打包时用babel做了polyfill，引入了`@babel/runtime`这个依赖，在peerDependencies的`react-transition-group`中会间接引入这个依赖，但如果用户没有安装`react-transition-group`，且项目用vite编译（不依赖babel）时，就会报错了。arco的最终打包产物也是依赖`@babel/runtime`的，应该把它放进 dependencies 里而不是让用户自己安装更合理，我们改下发个包哈~

**Comment by TinaPeach** [comment]
`@arco-design/mobile-react@2.31.2` 已修复
